### ISSUE TITLE
Harfbuzz

### ISSUE THREAD

**Issue by Frenzie** [koreader/crengine#224]
Do. Want.

(not spamming the other repo)
```
github.com/buggins/coolreader/pull/24
```

It looks amazingly uninvolved at a quick glance. (The PR is gigantic, but most of that is just harfbuzz itself.)

**Comment by robert00s** [comment]
Is it possible to integrate with our crengine repository?

**Comment by Frenzie** [comment]
I suspect that we haven't really touched the affected parts of lvfntman.cpp/h but I haven't checked yet.

See https://github.com/koreader/crengine/pull/122#issuecomment-372037385 for how to do that in a couple of minutes.

However, in our case it *would* require more involved changes in the koreader-base repo as well for it to actually build. But with any luck those commits will just integrate with no or minimal effort.

**Comment by poire-z** [comment]
> I suspect that we haven't really touched the affected parts of lvfntman.cpp/h

I did a bit in https://github.com/koreader/crengine/pull/212/files#diff-39c6d98ff2d0122472cff214e1510f8b . So that handling of soft-hyphens would need to be removed and put back after that patch.
I'm also not so sure about the lvtinydom.cpp IsUnicodeSpace() added space chars, see https://github.com/koreader/crengine/pull/220#issuecomment-407008884.
(it's been merged really quickly upstream, but we must be sure it's safe to use in our context).

Is that stuff all about and only kerning? That kind of ffff or ligature stuff?
https://raw.githubusercontent.com/tangrams/harfbuzz-example/master/img/capture.png
(in that case, I'm not at all excited :)
But if yes, and I dunno how much this is a _it must be rendered like that_  or a preference thing, but we may want to make it another toggable option.

Anyway, the fun will be for you FOC ([Friends of Cmake](https://en.wikipedia.org/wiki/Dead_Men_Don%27t_Wear_Plaid#Plot))

**Comment by Frenzie** [comment]
Much of the time that crengine looks a bit blah, as if you were looking at something on a computer screen even though E Ink can look as good as cheap newspaper, it's kerning and spacing related. So I'm inclined to think it could be potentially huge on the short term.

In the potential long term, Harfbuzz (or something like it) is what you need for RTL.

**Comment by cramoisi** [comment]
> Is that stuff all about and only kerning? That kind of ffff or ligature stuff?
(in that case, I'm not at all excited :)

I love this ligature thing so much :)

**Comment by Frenzie** [comment]
Also needs https://github.com/buggins/coolreader/pull/29

**Comment by poire-z** [comment]
I had a try with upstream 24+29, which applied almost ok, but we'll have to make it a toggable.
The render time for my big book that went with yesterday's PR from 11s to 5s goes up to 13s with harfbuzz.
Some screenshots (althought text looks always worse on the emulator than on eink):

Font Bitter, No Harfbuzz, with Font hinting auto:
![image](https://user-images.githubusercontent.com/24273478/44004253-f6f7e17e-9e5f-11e8-995b-5a4d279e3f1e.png)
Font Bitter, **Harfbuzz**, with Font hinting auto:
![image](https://user-images.githubusercontent.com/24273478/44004196-de781df4-9e5e-11e8-9fff-3647d1545c37.png)

Font Bitter, No Harfbuzz, with Font hinting off (nearly the same with native):
![image](https://user-images.githubusercontent.com/24273478/44004255-ffc93fbe-9e5f-11e8-8540-89b4393633df.png)
Font Bitter, **Harfbuzz**, with Font hinting off (nearly the same with native):
![image](https://user-images.githubusercontent.com/24273478/44004199-e7cbec78-9e5e-11e8-9dfd-51d453325204.png)

Bigger font size, Font Bitter, No Harfbuzz, with Font hinting auto:
![image](https://user-images.githubusercontent.com/24273478/44004237-c6ffb406-9e5f-11e8-94a4-3d302c874895.png)
Bigger font size, Font Bitter, **Harfbuzz**, with Font hinting auto:
![image](https://user-images.githubusercontent.com/24273478/44004225-644742fc-9e5f-11e8-96f4-45931965c2ed.png)

Bigger font size, Font Bitter, No Harfbuzz, with Font hinting off:
![image](https://user-images.githubusercontent.com/24273478/44004244-d1d97baa-9e5f-11e8-92f6-3f37b6c25be1.png)
Bigger font size, Font Bitter, **Harfbuzz**, with Font hinting off:
![image](https://user-images.githubusercontent.com/24273478/44004227-79fead1a-9e5f-11e8-844c-f6c420353b8d.png)

I'm personally not really sensitive to font rendering details. But I just felt it got worse with harfbuzz than without when using font hinting auto. Had to switch to font hinting off (or native) to get something correct.

Anyway, that was some home made build.
I couldn't figure out how to make cmake build harfbuzz.
Took some inspiration from @NiLuJe http://trac.ak-team.com/trac/browser/niluje/Configs/trunk/Kindle/Misc/x-compile.sh, and came up with this patch to base [base_harfbuzz1a.diff.txt](https://github.com/koreader/crengine/files/2281128/base_harfbuzz1a.diff.txt) and this patch to crengine (including upstream 24+29) [crengine_harfbuzz1a.diff.txt](https://github.com/koreader/crengine/files/2281129/crengine_harfbuzz1a.diff.txt)
kodev build kept making a static libharfbuzz.a. I had to manually do this to make a .so and be able to test:

In `/koreader/base/thirdparty/harfbuzz/build/x86_64-linux-gnu-debug/harfbuzz-prefix/src/harfbuzz $`

`FREETYPE_LIBS="-L/koreader/base/thirdparty/freetype2/build/x86_64-linux-gnu-debug/freetype2-prefix/src/freetype2-build -lfreetype" FREETYPE_CFLAGS=-I/koreader/base/thirdparty/freetype2/build/x86_64-linux-gnu-debug/freetype2-prefix/src/freetype2-build/include/freetype2 ./autogen.sh --enable-shared --without-coretext --without-uniscribe --without-cairo --without-glib --without-gobject --without-graphite2 --without-icu --with-freetype=yes`

So, if there's some interest for this harfbuzz rendering (that I can't appreciate :), it would be nice if @NiLuJe or @Frenzie could take over the base build of harfbuzz, because I don't want to start hating CMake as much as you do :)
(Also, I don't really get the interaction between freetype and harfbuzz: it needed, and I had a hardtime making it happen, to be linked against freetype. But I see in @NiLuJe above script and in other projects that people then relink freetype against harfbuzz. Would we need that too?!)

**Comment by NiLuJe** [comment]
FT itself can use HB to do... stuff... with it for the auto-hinter. I'm not quite sure to what extent, and if that even applies to Latin scripts at all.

**Comment by poire-z** [comment]
No idea :| (but I was using the .otf versions). Tried a few others (Noto, FreeSerif, Caecilia) and saw nothing much more striking, so went back to a font I'm confortable with.

**Comment by cramoisi** [comment]
@poire-z could you share your homemade built ?

**Comment by poire-z** [comment]
Dunno if it will work if you just drop them in your `koreader-emulator-x86_64-linux-gnu-debug/koreader/libs` or if there are hardcoded full paths: [libcrengine+harfbuzz.zip](https://github.com/koreader/crengine/files/2282150/libcrengine%2Bharfbuzz.zip)

**Comment by cramoisi** [comment]
tx !

**Comment by Frenzie** [comment]
The other repo has a ticket about the performance thing you noticed now:
```
https://github.com/buggins/coolreader/issues/37
```

**Comment by cramoisi** [comment]
Hi everyone. When enabling it I come across a lot of "concatenated" words (some words are displayed glued together); did some of you experienced this issue ?

**Comment by NiLuJe** [comment]
Yes, side-effect of using unhinted metrics with non-unhinted rendering.

Unfortunately, doing it right is [hard & expensive](https://github.com/koreader/crengine/pull/230).

**Comment by cramoisi** [comment]
Could I get it right by editing the font ?

**Comment by NiLuJe** [comment]
Nope.
