### ISSUE TITLE
Unsetting font for a class

### ISSUE THREAD

**Issue by Jellby** [koreader/crengine#362]
I have a book that uses an embedded font for small caps, like this:

```
@font-face {
  font-family: "KpRoman";
  src: url(../fonts/KpRomanSC-Regular.otf);
}
span.smallcaps {
  font-family: "KpRoman";
}
```

I'd like to create a user style tweak to disable the embedded font and use whatever default text font I choose, and its native small caps (if available). I don't want to disable embedded fonts completely, just for this case. I was successful with:

```
span.smallcaps {
  font-family: "none" !important;
  font-variant: small-caps;
}
```

But here are some questions:

1. Why do I need `!important`? Shouldn't a user style override book styles?
2. Why didn't `inherit` work instead of `"none"` (a non-existing font)?
3. Is there a better alternative way?

**Comment by poire-z** [comment]
We already have one, less selective than yours, that does it the same way you do:
https://github.com/koreader/koreader/blob/517c31e3e1233b171198ac9e267f9049f5c07f2f/frontend/ui/data/css_tweaks.lua#L316-L323

> Why do I need !important? Shouldn't a user style override book styles?

Because of the order of how these are applied, explained at:
https://github.com/koreader/koreader/issues/1430#issuecomment-634996740
It might not be the best, but it's driven by how things are implemented. So, we have to do with it...

> Why didn't inherit work instead of "none" (a non-existing font)?

Because everything is complicated :)
I also expected it to work - but it doesn't, because of how things are implement: these go into 2 styles slots: `font-family` for the `serif/sans-serif/monospace/inherit` enum - and `font-name` for the list of font names specified in that original font-family CSS property:
https://github.com/koreader/crengine/blob/a0d0d1f7ef4c2b996465e5b939efbe961430582b/crengine/src/lvstsheet.cpp#L2100-L2135
https://github.com/koreader/crengine/blob/a0d0d1f7ef4c2b996465e5b939efbe961430582b/crengine/src/lvstsheet.cpp#L2894-L2903
and they are then handled independantly:
https://github.com/koreader/crengine/blob/a0d0d1f7ef4c2b996465e5b939efbe961430582b/crengine/src/lvstsheet.cpp#L2992-L3005
May be we can do better, I dunno.
Note that we don't handle serif and sans-serif: everything is flagged as being sans-serif (because we can't know if a font is sans or serif) - except monospace (that we can now).

Something I noticed a few days ago is that when you use the above style tweak, if your main font is monospace, it won't be used - as setting NoSuchFont as the font name, and defaulting it to sans-serif, and not finding it, any other sans-serif font (so, not the main monospace font) will be used instead...

> Is there a better alternative way?

Not that I know of.

**Comment by poire-z** [comment]
Was looking at this, and there's something that's bugging me.

I added https://github.com/koreader/crengine/commit/fe6efab20, which might be bogus (and part of the reason `inherit !important` does not work).
I added it to solve https://github.com/koreader/crengine/pull/310#issuecomment-533713120.
It's probably wrong dropping `inherit` - and may be we should drop it only when there are font names before - OR otherwise ignore the font names...

While testing what browsers do with:
```html
<!DOCTYPE html>
<html>
<head>
<style>
body { font-family: "Noto Sans", sans-serif; }
div { font-family: "Gentium Book Basic"; color: blue; }
div.reset { font-family: inherit; color: green; }
p { font-family: inherit !important; color: green !important; }
p.gentium { font-family: "Gentium Book Basic"; color: blue; }
blockquote.gentiuminherit { font-family: "Gentium Book Basic", inherit; color: blue; }
blockquote.inexistantinherit { font-family: "NonExistant", inherit; color: red; }
</style>
</head>
<body>

This is in the BODY Sans.
<div>This is some text in a DIV Gentium</div>
<div class="reset">This is some text in a DIV.reset, inherit=Sans</div>
<p>This is some text in a P inherit=Sans</p>
<p class="gentium">This is some text in a P.gentium, but prevented cause inherit !important, so=Sans</p>

<blockquote>This is some text in a BLOCKQUOTE</blockquote>
<blockquote class="gentiuminherit">This is some text in a BLOCKQUOTE gentium-inherit</blockquote>
<blockquote class="inexistantinherit">This is some text in a BLOCKQUOTE inexistant-inherit</blockquote>
</body>
</html>
```
I get different things with Calibre (on the left) vs Firefox (on the right):
![image](https://user-images.githubusercontent.com/24273478/107864817-5a8c6c00-6e60-11eb-83bd-21f3ccf3d2df.png)

The `blockquote.gentiuminherit { font-family: "Gentium Book Basic", inherit; }` is bugging me... and it's the same as in the book I tried to fix which has `body { font-family: "Adobe Garamond Pro (embedded)", inherit; }`.

It seems Calibre just drop the `inherit` (when you inspect the element's style, the "inherit" is not there).

While Firefox (and Edge) make `inherit` kill everything else - or not:
![image](https://user-images.githubusercontent.com/24273478/107864931-e05ce700-6e61-11eb-9dbf-e67c24a16278.png)
the yellow triangle says: invalid property value - to it just inherits it by default.

The CSS2 specs https://www.w3.org/TR/CSS2/fonts.html#font-family-prop mentions just:
`Value: [[ <family-name> | <generic-family> ] [, <family-name>| <generic-family>]* ] | inherit`
which could indicate that `inherit` is an alternative to everything else, and must be standalone.
CSS3 doesn't mention that, but doesn't mention `inherit` at all...

So what to do with this (before going at fixing this issue)?
I guess we should follow Calibre, as there must be books like this one in the wild.
Thoughts, @Jellby @Frenzie ?

**Comment by Jellby** [comment]
If I remember correctly, a `<blockquote>` is not allowed to have bare text or inline elements inside, it can only have block elements (though they could be styled as `display: inline`, I guess). I don't know if it has anything to do with it, probably not, since the color is applied.

The CSS3 document doesn't explicitly mention `inherit`, but it says:

> Font family names that happen to be the same as keyword value (‘inherit’, ‘serif’, etc.) must be quoted to prevent confusion with the keywords with the same names.

Maybe the meaning and usage of `inherit` is specified elsewhere? [yep, [here](https://www.w3.org/TR/css3-values/#common-keywords)] Or maybe a clarification could be requested. Another thing is that at least the ePub 2 specification requires CSS2 support, I'm not up to date with ePub 3. I believe accepting `inherit` as a value in the list of fonts (or even just ignoring it as an "unknown keyword") is a more reasonable behavior than dropping the whole property as invalid.

**Comment by Frenzie** [comment]
> I guess we should follow Calibre, as there must be books like this one in the wild.

Before investigating, what calibre version are you using? Keep in mind calibre 3.x uses possibly quite outdated QtWebKit while calibre 4.x has switched to Blink (QtWebEngine). This means that a priori, the likelihood is greater that calibre 3.x contains a bug than that modern Fx does.

And remember my mantra, WDPD? ;-D (What does Prince do?)

> I'm not up to date with ePub 3.

Besides a few extensions it simply refers to HTML5/CSS3.

**Comment by poire-z** [comment]
And old Calibre Portable 3.33.1.
Don't have Prince, don't know what it does.
But the thing is that some books has been made in the past, and tested against these old calibre versions. So, I guess a few might have these invalid properties.

>  I believe accepting inherit as a value in the list of fonts (or even just ignoring it as an "unknown keyword") is a more reasonable behavior than dropping the whole property as invalid.

I kinda agree we should do that: if there are valid font names (probably embedded fonts), it's a publisher error to have added "inherit" to it, dont punish the publisher & user: just use the embedded fonts.

**Comment by Frenzie** [comment]
### Prince
![Screenshot_2021-02-14_12-10-40](https://user-images.githubusercontent.com/202757/107875006-ad484100-6ebd-11eb-8f0d-f41ebfc3ea0e.png)

[bla.pdf.zip](https://github.com/koreader/crengine/files/5977600/bla.pdf.zip)

**Comment by Frenzie** [comment]
> CSS3 https://drafts.csswg.org/css-fonts-3/#font-family-prop doesn't mention that, but doesn't mention inherit at all...

It does, it says it's inherited, with all that entails (i.e., the same thing somewhat redundantly but more clearly stated in CSS2).

https://drafts.csswg.org/css-cascade-5/#valdef-all-inherit

**Comment by NiLuJe** [comment]
Yeah, I'd check with Calibre 5, because Calibre 3 is no longer old, it's downright prehistoric ;).

(But, as @Frenzie said, Calibre 5 uses QtWebEngine, i.e., Blink, so it should roughly match modern Chrome).

**Comment by NiLuJe** [comment]
As expected, modern browsery ;)

![Screenshot_20210214_190654](https://user-images.githubusercontent.com/111974/107884953-de456780-6ef7-11eb-866a-f40905728568.png)

**Comment by poire-z** [comment]
Thanks.
Looks like that text book from [mobiread](https://www.mobileread.com/forums/showpost.php?p=3892357&postcount=199) has [been updated](https://goo.gl/RkSJ7R). It's 191002 version uses only:
`font-family: "Adobe Garamond Pro (embedded)";` with the "inherit" (present in its 190405 version) removed.
Just to be sure, can you see how the 190405 version from the "Old releases" folder do on Calibre5 ? I guess you don't get the nice Adobe font.

(But that's not a reason to not try to behave well with previous versions :)

**Comment by NiLuJe** [comment]
@poire-z: Yep, Garamond only in `191002`, my user-preferred font in the older version.

**Comment by poire-z** [comment]
OK, our (my) parsing of `!important` and `inherit` was a bit loosy. I have fixed that.

Putting here for reference the results of my updated parsing, before I remove those printf:
```
font-family: "Droid Sans Mono", "Liberation Mono", "DeJaVu Sans Mono", monospace
  3: #monospace#
  2: #DeJaVu Sans Mono#
  1: #Liberation Mono#
  0: #Droid Sans Mono#
  n=5 imp=0 strValue="Droid Sans Mono", "Liberation Mono", "DeJaVu Sans Mono"

font-family: "Noto Sans", sans-serif
  1: #sans-serif#
  0: #Noto Sans#
  n=2 imp=0 strValue="Noto Sans"

font-family: "Gentium Book Basic"
  0: #Gentium Book Basic#
  n=-1 imp=0 strValue="Gentium Book Basic"

font-family: inherit
  0: #inherit#
  n=0 imp=0 strValue=

font-family: inherit
  0: #inherit#
  n=0 imp=0 strValue=

font-family: inherit !important
  0: #inherit !important#
  n=0 imp=40000000 strValue=

font-family: "Gentium Book Basic"
  0: #Gentium Book Basic#
  n=-1 imp=0 strValue="Gentium Book Basic"

font-family: "Gentium Book Basic", inherit
  1: #inherit#
  0: #Gentium Book Basic#
  n=-1 imp=0 strValue="Gentium Book Basic"

font-family: "NonExistant", inherit
  1: #inherit#
  0: #NonExistant#
  n=-1 imp=0 strValue="NonExistant"

font-family: "Gentium Book Basic" !important
  1: #!important#
  0: #Gentium Book Basic#
  n=-1 imp=40000000 strValue="Gentium Book Basic"

font-family: serif !important
  0: #serif !important#
  n=1 imp=40000000 strValue=

font-family: Diavlo !important
  0: #Diavlo !important#
  n=-1 imp=40000000 strValue="Diavlo"

font-family: "Gentium Book Basic", Diavlo !important
  1: #Diavlo !important#
  0: #Gentium Book Basic#
  n=-1 imp=40000000 strValue="Gentium Book Basic", "Diavlo"

font-family: "Gentium Book Basic", Diavlo, "Noto Sans" !important
  3: #!important#
  2: #Noto Sans#
  1: #Diavlo#
  0: #Gentium Book Basic#
  n=-1 imp=40000000 strValue="Gentium Book Basic", "Diavlo", "Noto Sans"

font-family: "Gentium Book Basic", Diavlo, "Noto Sans", cursive !important
  3: #cursive !important#
  2: #Noto Sans#
  1: #Diavlo#
  0: #Gentium Book Basic#
  n=3 imp=40000000 strValue="Gentium Book Basic", "Diavlo", "Noto Sans"
```
