### ISSUE TITLE
Style tag with CDATA doesn't work

### ISSUE THREAD

**Issue by johnbeard** [koreader/crengine#396]
Some EPUBs, for example those from Wikisource ([example](https://wsexport.wmflabs.org/book.php?lang=en&format=epub-3&page=Apollonius_of_Tyana_-_The_Pagan_Christ_of_the_Third_Century%2FIntroduction)) have `<style>` elements in the `<head>` of the XHTML files that have [CDATA](https://en.wikipedia.org/wiki/CDATA) in them like this:

```
<style><![CDATA[.class{text-align: foo;}]]></style>
```
None of the contained styling is applied. However changing to simply:
```
<style>.class{text-align: foo;}</style>
```
works fine.

**Comment by poire-z** [comment]
There is this, which looks a bit strange:
https://github.com/koreader/crengine/blob/4a970f08a429593186d8c52b84277cd63769bc4c/crengine/src/lvxml.cpp#L2992-L2997

Does it work if you add `type="text/css"` in `<style type="text/css">` ?

**Comment by johnbeard** [comment]
Yes, that fixes it!

I'm unsure if this means it's invalid EPUB, but as far as I know there's no limitation on CDATA to only be in `text/css` style tags, even if that is where it is usually found.

**Comment by NiLuJe** [comment]
I suppose that's to avoid parsing CDATA content when it's in the middle of stuff and not actually useful/styling?

**Comment by poire-z** [comment]
Don't know much about CDATA - but the parser stuff might not be super XML-specs perfect - it's just good enough for the kind of data we meet.
So, the question for the less risky workaround:
are there other kind of `<STYLE>` tags, without any `type` or a `type!=text/css`, where we would need to _not_ trim/skip `[CDATA]` ?
I guess the answer is no :) and we might just remove `&&attrvalue.compare("text/css")==0`

> to avoid parsing CDATA

This bit of code is just skipping it at start - not even at end, because I guess the CSS parser will be just fine with garbage at the end.

**Comment by johnbeard** [comment]
Since CSS is at the XML level, and not at the CSS (or whatever other style exits) level, I can't see how it would be valid data.
OTOH, the code as written junks the next 7 chars after `<!` as long as the first one is `[`, so, I guess it's vulnerable to misinterpreting something that starts `[notcdata` as `ta`.

So perhaps the check should make sure that it's really a CDATA section?

**Comment by johnbeard** [comment]
https://www.w3schools.com/tags/att_style_type.asp says `text/css` is the only valid value of a style tag's `type` attribute "for now".

**Comment by poire-z** [comment]
When this code meets:
`<style><![CDATA[validstuff]]></style>`
at the `<`, it will look ahead for `[` and if found, will skip 7 bytes, so it will give the parser as text what's after these 7 bytes: `validstuff]]` . That will be parsed later by the CSS parser, which (given how it works) will be fine with the traling garbage `]]` and just ignore it.

> vulnerable to misinterpreting something that starts [notcdata as ta.

Yes, and I guess we can do with that. We don't want to be super solid (we're supposed books to be valid XML, we can assume we're not in the jungle), but we want to be fast - so not do to much work.

**Comment by johnbeard** [comment]
Anyway, at least for CSS, it's *highly* unlikely that the CSS starts `<x[` (where x is any char), since that's a jolly odd selector (pretty sure `<` isn't a "thing" in CSS), to say the least.

**Comment by Frenzie** [comment]
> are there other kind of <STYLE> tags, without any type or a type!=text/css, where we would need to not trim/skip [CDATA] ?
I guess the answer is no :) and we might just remove &&attrvalue.compare("text/css")==0

Empty is the same as text/css in (X)HTML5, but in the type of XHTML that EPUB is in principle a style element without a `type` attribute should be dropped. In practice it's better we didn't.

Basically it's:

* empty → text/css
* text/css → text/css
* something else → probably just a mistake/typo, but technically not supported, better double check what browsers have decided to do with the Wild West Web out there

The CDATA stuff should of course always be stripped since that's just XML. :-)

**Comment by poire-z** [comment]
Well, trying to handle CDATA correctly, and wanting to check how browsers do it, I somehow see browsers do ignore, skip, don't show the CDATA content...
My test file: [test-cdata.html.txt](https://github.com/koreader/crengine/files/5647042/test-cdata.html.txt) containing CDATA between the HR (it's possible I have some typo/misclosing/mismatch that cause that, but then the HR shouldn't be showing...).

IE11 | Firefox | KOReader current
<kbd>![image](https://user-images.githubusercontent.com/24273478/101243148-853ea380-36fe-11eb-9bc9-e2506a4fd175.png)</kbd>

No matter the DOCTYPE i use. I can't figure how dependant it is on that.
There are a few Firefox bugs mentionning that, that I don't want to understand :) 
https://www.google.com/search?hl=en&num=25&q=firefox+cdata+style

I somehow feel they should be handled and shown. I guess it's a handy way to include code like content without having to escape `<` and `&` ...

So, dunno :/

**Comment by poire-z** [comment]
And this is what we would get if we would parse CDATA as text, just looking for the text node end marker ,`]]>` instead of just `>` (still bogus in my quick try), and just not calling PreProcessXmlString() (which replaces XML entities and some other space/CR stuff) - which looks to me like it's all there is with CDATA.

![image](https://user-images.githubusercontent.com/24273478/101243554-84f3d780-3701-11eb-9c79-19c81464bbde.png)

**Comment by poire-z** [comment]
With more proper boundaries handling:
vim | Firefox | KOReader | KOReader DOM
<kbd>![image](https://user-images.githubusercontent.com/24273478/101244033-5aefe480-3704-11eb-9527-76a9e795453d.png)</kbd>

<kbd>![image](https://user-images.githubusercontent.com/24273478/101244131-ea959300-3704-11eb-89d0-fff4bd8406c7.png)</kbd>

So, which handling (proper, or ignoring) is right or best? :/

**Comment by Frenzie** [comment]
You have to name it .xhtml to trigger proper behavior.

![Screenshot_2020-12-05_15-16-11](https://user-images.githubusercontent.com/202757/101245394-d9508480-370c-11eb-961b-f9dca68e5826.png)

**Comment by Frenzie** [comment]
Or .xml.

Otherwise it's treated as HTML.

**Comment by Frenzie** [comment]
Anyway, it shouldn't be ignored. CDATA is there to tell the parser that whatever's inside might break regular XML. See https://developer.mozilla.org/en-US/docs/Archive/Web/Properly_Using_CSS_and_JavaScript_in_XHTML_Documents_ if you want the nitty gritty.

**Comment by poire-z** [comment]
Must not be my day :) I can't get .xml or .xhtml to show (I get them proposed to be downloaded) - and you url gives me "Not found" :)
So, if we're not going to distinguish between html and xml, you're saying it's better to have CDATA handled as in my last screenshots above ? And I can commit this?

It's hard to know if the thing in CDATA is crap (program output, comments) or valuable stuff (raw content, wrapped CSS). I always prefer to show more (so one can estimate if it's crap or not) than taking the risk of hiding stuff, and not know there is (possibly valuable) stuff that is hidden.

**Comment by Frenzie** [comment]
It's probably better than before? :-)
![Screenshot_2020-12-05_15-52-26](https://user-images.githubusercontent.com/202757/101246176-e4f27a00-3711-11eb-87e5-159194200ff7.png)

**Comment by Frenzie** [comment]
Your file as given:
![Screenshot_2020-12-05_15-56-17](https://user-images.githubusercontent.com/202757/101246275-8679cb80-3712-11eb-86f2-0541e8b21e2a.png)

Your file with the offending part removed:
![Screenshot_2020-12-05_15-56-56](https://user-images.githubusercontent.com/202757/101246276-87126200-3712-11eb-9704-27456376a829.png)

**Comment by poire-z** [comment]
> Your file with the offending part removed:

Thanks, so that shall be my target result :) I'm not far from it!

Looks like I still need to go thru preProcessXMLString to strip \n and consecutive spaces - we should just skip HTML entities decoding. CDATA is not `<PRE>`:
<kbd>![image](https://user-images.githubusercontent.com/24273478/101247713-5a167d00-371b-11eb-8ded-22ba93171038.png)</kbd>

**Comment by poire-z** [comment]
End result with updated #397 with [test-cdata.html.txt](https://github.com/koreader/crengine/files/5647419/test-cdata.html.txt)
<kbd>![image](https://user-images.githubusercontent.com/24273478/101258205-41a96100-3721-11eb-9e1f-adf63b3c025b.png)</kbd>
