### ISSUE TITLE
side effect for hold segfault fix

### ISSUE THREAD

**Issue by houqp** [koreader/crengine#67]
@frankyifei found a bug introduced by : https://github.com/koreader/crengine/commit/ee91e8e8c70ebe7d8d6ef99b0dc9a14752a6854f

> I noticed that this commit introduced the links' bug that you fixed with next commit, can we do this more elegantly?

Let's brain storm a better way to fix the segfault here.

**Comment by poire-z** [comment]
For accuracy: I'm quite sure the "links being clickable outside bounds" bug was there before I added the fix for segfault hold (opened https://github.com/koreader/koreader/issues/2412 in december). At least for links in div, but I also think it was there for links in list-items.
But i'm fine with my amateurish patches being reworked, as long as both bugs stay fixed :)

**Comment by frankyifei** [comment]
My bad, I thought I had deleted that comment. It was something wrong with
my test file.

2017年2月4日 01:33，"poire-z" <notifications@github.com>写道：

**Comment by Frenzie** [comment]
Problem with test file = closing this. ;-)
